export interface IndustryData {
    name: string;
    positions: string[];
}

export const industries: IndustryData[] = [
    {
        name: "Technology & Software (เทคโนโลยีและซอฟต์แวร์)",
        positions: [
            "Software Engineer",
            "Frontend Developer",
            "Backend Developer",
            "Full Stack Developer",
            "Mobile App Developer (iOS/Android)",
            "DevOps Engineer",
            "Cloud Architect",
            "System Administrator",
            "QA Engineer / Tester",
            "Cybersecurity Specialist",
            "Data Scientist",
            "Data Analyst",
            "Data Engineer",
            "Machine Learning Engineer",
            "AI Specialist",
            "Blockchain Developer",
            "Game Developer",
            "UX/UI Designer",
            "Product Manager (Tech)",
            "Scrum Master",
            "IT Support Specialist",
            "Network Engineer",
            "Solution Architect",
            "CTO (Chief Technology Officer)",
        ],
    },
    {
        name: "Digital Marketing & Advertising (การตลาดและโฆษณา)",
        positions: [
            "Digital Marketing Specialist",
            "Social Media Manager",
            "Content Creator / Writer",
            "SEO/SEM Specialist",
            "Marketing Manager",
            "Brand Manager",
            "Copywriter",
            "Graphic Designer",
            "Creative Director",
            "Media Planner / Buyer",
            "Public Relations (PR) Specialist",
            "Event Planner / Organizer",
            "Market Research Analyst",
            "Account Executive (Advertising)",
            "Influencer Marketing Specialist",
            "E-commerce Manager",
            "Growth Hacker",
        ],
    },
    {
        name: "Sales & Business Development (การขายและพัฒนาธุรกิจ)",
        positions: [
            "Sales Representative",
            "Sales Manager",
            "Business Development Manager (BD)",
            "Account Manager",
            "Account Executive",
            "Customer Success Manager",
            "Sales Engineer",
            "Telesales / Telemarketing",
            "Retail Sales Associate",
            "Area Sales Manager",
            "Key Account Manager",
            "Partnership Manager",
        ],
    },
    {
        name: "Finance, Banking & Accounting (การเงิน การธนาคาร และบัญชี)",
        positions: [
            "Accountant (General/Tax/Cost)",
            "Financial Analyst",
            "Auditor (Internal/External)",
            "Bookkeeper",
            "Investment Banker",
            "Financial Controller",
            "Risk Management Specialist",
            "Credit Analyst",
            "Loan Officer",
            "Relationship Manager (Banking)",
            "Actuary",
            "Trader / Broker",
            "Payroll Specialist",
            "CFO (Chief Financial Officer)",
        ],
    },
    {
        name: "Human Resources (ทรัพยากรบุคคล)",
        positions: [
            "HR Manager",
            "Recruiter / Talent Acquisition",
            "HR Generalist",
            "Compensation & Benefits Specialist",
            "Learning & Development (L&D) Specialist",
            "HR Business Partner (HRBP)",
            "Employee Relations Specialist",
            "HR Coordinator",
            "Payroll Officer",
            "Organizational Development Specialist",
        ],
    },
    {
        name: "Engineering & Manufacturing (วิศวกรรมและการผลิต)",
        positions: [
            "Mechanical Engineer",
            "Electrical Engineer",
            "Civil Engineer",
            "Industrial Engineer",
            "Chemical Engineer",
            "Production Manager",
            "Quality Control (QC) / Quality Assurance (QA)",
            "Maintenance Engineer",
            "Safety Officer (JorPor)",
            "Plant Manager",
            "R&D Engineer",
            "Automation Engineer",
            "Project Engineer",
        ],
    },
    {
        name: "Logistics, Supply Chain & Procurement (โลจิสติกส์และจัดซื้อ)",
        positions: [
            "Supply Chain Manager",
            "Logistics Manager",
            "Procurement / Purchasing Specialist",
            "Warehouse Manager",
            "Inventory Control Specialist",
            "Import/Export Coordinator",
            "Shipping Coordinator",
            "Transport Manager",
            "Driver (Truck/Delivery)",
            "Customs Specialist",
        ],
    },
    {
        name: "Healthcare, Medical & Wellness (สุขภาพและการแพทย์)",
        positions: [
            "Doctor / Physician",
            "Registered Nurse",
            "Pharmacist",
            "Medical Technologist",
            "Physical Therapist",
            "Nutritionist / Dietitian",
            "Dentist",
            "Veterinarian",
            "Healthcare Administrator",
            "Medical Sales Representative",
            "Psychologist",
        ],
    },
    {
        name: "Administrative & Operations (ธุรการและการจัดการทั่วไป)",
        positions: [
            "Administrative Assistant",
            "Office Manager",
            "Executive Assistant / Secretary",
            "Receptionist",
            "Operations Manager",
            "Project Coordinator",
            "Data Entry Clerk",
            "General Manager",
            "Customer Service Representative",
            "Call Center Agent",
        ],
    },
    {
        name: "Education & Training (การศึกษาและฝึกอบรม)",
        positions: [
            "Teacher / Instructor",
            "Tutor",
            "University Lecturer / Professor",
            "Education Administrator",
            "Instructional Designer",
            "Corporate Trainer",
            "Guidance Counselor",
            "Researcher",
            "Librarian",
        ],
    },
    {
        name: "Design, Arts & Media (ออกแบบ ศิลปะ และสื่อ)",
        positions: [
            "Graphic Designer",
            "Interior Designer",
            "Fashion Designer",
            "Product Designer",
            "Video Editor",
            "Photographer / Videographer",
            "Animator / Motion Graphic Artist",
            "Art Director",
            "Journalist / Reporter",
            "Translator / Interpreter",
        ],
    },
    {
        name: "Legal & Compliance (กฎหมาย)",
        positions: [
            "Lawyer / Attorney",
            "Legal Consultant",
            "Paralegal",
            "Compliance Officer",
            "Corporate Secretary",
            "Judge / Magistrate",
        ],
    },
    {
        name: "Tourism, Hotel & F&B (ท่องเที่ยว โรงแรม และอาหาร)",
        positions: [
            "Hotel Manager",
            "Front Desk Officer",
            "Chef / Cook",
            "Food & Beverage Manager",
            "Barista / Bartender",
            "Flight Attendant",
            "Tour Guide",
            "Travel Agent",
            "Event Coordinator",
            "Housekeeping Supervisor",
        ],
    },
    {
        name: "Real Estate & Property (อสังหาริมทรัพย์)",
        positions: [
            "Real Estate Agent / Broker",
            "Property Manager",
            "Real Estate Developer",
            "Valuation Surveyor",
            "Building Manager",
            "Leasing Consultant",
        ],
    },
    {
        name: "Agriculture & Environment (เกษตรกรรมและสิ่งแวดล้อม)",
        positions: [
            "Agriculturalist",
            "Farm Manager",
            "Environmental Scientist",
            "Geologist",
            "Forestry Specialist",
            "Sustainability Consultant",
        ],
    },
];
