// lib/jobs.ts
export type JobType = "Full-Time" | "Part-Time" | "Contract";
export type JobLevel = "Junior" | "Mid" | "Senior" | "Expert";
export type WorkMode = "Onsite" | "Hybrid" | "Remote";
export type SortOption = "recent" | "salary" | "applicants";

export type JobCardData = {
  id: number;
  company: string;
  company_id?: string; // Company UUID for linking to company profile
  post_id?: string; // Post UUID for application tracking
  role: string;
  location: string;
  onsite: WorkMode;
  rate: string;
  salarySort?: number;
  type: JobType;
  applicants: string; // "20 /50"
  level: JobLevel;
  time: string;
  sortIndex: number;
  tags?: string[];
  description: string[];
  // New fields for job post details
  responsibilities?: string;
  qualifications?: string;
  benefits?: string;
  // Fields for logged-in users
  salaryReal?: string;
  contactPerson?: string;
  aiMatchReason?: string;
};

export const SAMPLE_JOBS: JobCardData[] = [
  {
    id: 1,
    company: "Hatypo Studio",
    role: "UI Designer",
    location: "Surakarta, ID",
    onsite: "Onsite",
    rate: "$10 /hour",
    salarySort: 10,
    type: "Part-Time",
    applicants: "20 /50",
    level: "Expert",
    time: "1h ago",
    sortIndex: 1,
    tags: ["Figma", "Design System", "Illustration"],
    description: [
      "Collaborate with the Marketing team to deliver wireframes, user journeys, and UI mock-ups.",
      "Establish best practices for high-performing websites with SEO & Content.",
      "Partner with Front-End Developers to ensure quality & speed.",
    ],
    salaryReal: "$15 - $25 /hour",
    contactPerson: "Sarah Jenkins (HR Manager)",
    aiMatchReason: "Your portfolio shows strong Figma skills which matches the requirements.",
  },
  {
    id: 2,
    company: "Archo",
    role: "UI Designer",
    location: "Yogyakarta, ID",
    onsite: "Onsite",
    rate: "$5 /hour",
    salarySort: 5,
    type: "Part-Time",
    applicants: "9 /40",
    level: "Expert",
    time: "2h ago",
    sortIndex: 2,
    tags: ["UI Kit", "Brand", "Landing Pages"],
    description: [
      "Bachelor's degree in Design or related field.",
      "Active portfolio showcasing responsive design.",
      "Experience collaborating with cross-functional teams.",
    ],
    salaryReal: "$8 - $12 /hour",
    contactPerson: "Budi Santoso (Design Lead)",
    aiMatchReason: "Experience with UI Kits is a strong plus.",
  },
  {
    id: 3,
    company: "Nova Labs",
    role: "Product Designer",
    location: "Bangkok, TH",
    onsite: "Hybrid",
    rate: "$2,000–2,800 /mo",
    salarySort: 2600,
    type: "Full-Time",
    applicants: "12 /40",
    level: "Senior",
    time: "3h ago",
    sortIndex: 3,
    tags: ["Product Discovery", "Design Tokens", "R&D"],
    description: [
      "Own end-to-end product design from discovery to delivery.",
      "Create systemized components and maintain the design system.",
      "Run usability tests, synthesize findings, and iterate quickly.",
    ],
    salaryReal: "$2,500 - $3,500 /mo",
    contactPerson: "Nopa (Product Head)",
    aiMatchReason: "Your background in Design Tokens aligns perfectly.",
  },
  {
    id: 4,
    company: "ByteBeam",
    role: "Frontend Engineer",
    location: "Remote",
    onsite: "Remote",
    rate: "$1,800–2,400 /mo",
    salarySort: 2100,
    type: "Contract",
    applicants: "35 /100",
    level: "Mid",
    time: "5h ago",
    sortIndex: 4,
    tags: ["Next.js", "TypeScript", "GSAP"],
    description: [
      "Build motion-rich web apps with Next.js + GSAP.",
      "Collaborate with designers on component libraries.",
      "Ship fast with strong testing discipline.",
    ],
    salaryReal: "$2,200 - $3,000 /mo",
    contactPerson: "Alex Chen (CTO)",
    aiMatchReason: "Strong Next.js and GSAP projects in your GitHub.",
  },
  {
    id: 5,
    company: "Helio AI",
    role: "ML Engineer",
    location: "Bangkok, TH",
    onsite: "Hybrid",
    rate: "$3,500–4,200 /mo",
    salarySort: 3850,
    type: "Full-Time",
    applicants: "7 /25",
    level: "Senior",
    time: "6h ago",
    sortIndex: 5,
    tags: ["PyTorch", "LLM", "RAG"],
    description: [
      "Train & evaluate LLM pipelines.",
      "Optimize inference & memory footprint.",
      "Work with product to ship ML features.",
    ],
    salaryReal: "$4,000 - $5,000 /mo",
    contactPerson: "Dr. Somchai (AI Director)",
    aiMatchReason: "Your research on RAG is highly relevant.",
  },
  {
    id: 6,
    company: "Craftline",
    role: "UX Researcher",
    location: "Singapore, SG",
    onsite: "Onsite",
    rate: "$3,000–3,800 /mo",
    salarySort: 3400,
    type: "Full-Time",
    applicants: "4 /15",
    level: "Junior",
    time: "8h ago",
    sortIndex: 6,
    tags: ["User Interviews", "JTBD", "Usability"],
    description: [
      "Run discovery interviews and usability tests.",
      "Synthesize insights into product direction.",
      "Collaborate with design & PM on roadmap.",
    ],
    salaryReal: "$3,500 - $4,200 /mo",
    contactPerson: "Lisa Wong (Head of UX)",
    aiMatchReason: "Good experience with user interviews.",
  },
  {
    id: 7,
    company: "ChaoPhraya Fintech",
    role: "Backend Engineer (Go)",
    location: "Samut Prakan, TH",
    onsite: "Hybrid",
    rate: "฿90,000–120,000 /mo",
    salarySort: 105000,
    type: "Full-Time",
    applicants: "11 /30",
    level: "Senior",
    time: "1d ago",
    sortIndex: 7,
    tags: ["Go", "PostgreSQL", "Kubernetes"],
    description: [
      "Own microservices and event-driven architecture.",
      "Improve reliability and observability (Grafana/Prometheus).",
      "Work closely with product to scope and deliver features.",
    ],
    salaryReal: "฿100,000 - ฿140,000 /mo",
    contactPerson: "K. Prasit (VP Engineering)",
    aiMatchReason: "Solid Go and Kubernetes experience.",
  },
  {
    id: 8,
    company: "Siam Commerce",
    role: "Full-Stack Developer",
    location: "Chiang Mai, TH",
    onsite: "Onsite",
    rate: "฿55,000–75,000 /mo",
    salarySort: 65000,
    type: "Full-Time",
    applicants: "18 /60",
    level: "Mid",
    time: "1d ago",
    sortIndex: 8,
    tags: ["React", "Node.js", "MySQL"],
    description: [
      "Implement storefront UI and internal dashboards.",
      "Write clean APIs and integrate third-party services.",
      "Participate in code reviews and CI/CD pipelines.",
    ],
    salaryReal: "฿60,000 - ฿80,000 /mo",
    contactPerson: "K. Malee (Tech Lead)",
    aiMatchReason: "Full-stack skills match the requirements.",
  },
  {
    id: 9,
    company: "Eastern Pixels",
    role: "Motion Designer",
    location: "Chonburi, TH",
    onsite: "Onsite",
    rate: "฿1,200 /day",
    salarySort: 1200,
    type: "Contract",
    applicants: "6 /20",
    level: "Junior",
    time: "2d ago",
    sortIndex: 9,
    tags: ["After Effects", "Premiere", "Brand"],
    description: [
      "Create short-form motion for campaign assets.",
      "Work with copy and brand to align on storyboards.",
      "Export and deliver in required social formats.",
    ],
    salaryReal: "฿1,500 /day",
    contactPerson: "Art Director",
    aiMatchReason: "Creative portfolio.",
  },
  {
    id: 10,
    company: "Andaman Cloud",
    role: "DevOps Engineer",
    location: "Phuket, TH",
    onsite: "Remote",
    rate: "$2,500–3,200 /mo",
    salarySort: 2850,
    type: "Contract",
    applicants: "9 /25",
    level: "Mid",
    time: "2d ago",
    sortIndex: 10,
    tags: ["AWS", "Terraform", "CI/CD"],
    description: [
      "Own IaC and environment provisioning.",
      "Optimize build times and deployment safety.",
      "Implement monitoring and alerting best practices.",
    ],
    salaryReal: "$3,000 - $3,800 /mo",
    contactPerson: "DevOps Lead",
    aiMatchReason: "AWS certification.",
  },
  {
    id: 11,
    company: "Isan Robotics",
    role: "Embedded Engineer",
    location: "Nakhon Ratchasima, TH",
    onsite: "Onsite",
    rate: "฿70,000–95,000 /mo",
    salarySort: 82000,
    type: "Full-Time",
    applicants: "3 /12",
    level: "Senior",
    time: "3d ago",
    sortIndex: 11,
    tags: ["C/C++", "RTOS", "CAN bus"],
    description: [
      "Develop firmware for industrial robotics.",
      "Collaborate with electrical engineers for board bring-up.",
      "Contribute to safety and failover features.",
    ],
    salaryReal: "฿80,000 - ฿110,000 /mo",
    contactPerson: "Engineering Manager",
    aiMatchReason: "Embedded systems background.",
  },
  {
    id: 12,
    company: "Thonburi HealthTech",
    role: "Data Analyst",
    location: "Bangkok, TH",
    onsite: "Hybrid",
    rate: "฿45,000–65,000 /mo",
    salarySort: 55000,
    type: "Full-Time",
    applicants: "22 /80",
    level: "Junior",
    time: "3d ago",
    sortIndex: 12,
    tags: ["SQL", "dbt", "Tableau"],
    description: [
      "Model datasets for self-serve analytics.",
      "Work with clinicians to define metrics.",
      "Automate reports and dashboards.",
    ],
    salaryReal: "฿50,000 - ฿70,000 /mo",
    contactPerson: "Data Lead",
    aiMatchReason: "Strong SQL skills.",
  },
  {
    id: 13,
    company: "Rayong Energy",
    role: "Site Reliability Engineer",
    location: "Rayong, TH",
    onsite: "Hybrid",
    rate: "$2,200–2,900 /mo",
    salarySort: 2550,
    type: "Full-Time",
    applicants: "5 /18",
    level: "Mid",
    time: "4d ago",
    sortIndex: 13,
    tags: ["SRE", "GCP", "Observability"],
    description: [
      "Define SLOs/SLIs and error budgets.",
      "Reduce toil through automation.",
      "Incident response and postmortems.",
    ],
    salaryReal: "$2,500 - $3,200 /mo",
    contactPerson: "SRE Manager",
    aiMatchReason: "GCP experience.",
  },
  {
    id: 14,
    company: "Ayutthaya Heritage",
    role: "Content Strategist (EN/TH)",
    location: "Phra Nakhon Si Ayutthaya, TH",
    onsite: "Onsite",
    rate: "฿30,000–45,000 /mo",
    salarySort: 37500,
    type: "Full-Time",
    applicants: "14 /50",
    level: "Junior",
    time: "5d ago",
    sortIndex: 14,
    tags: ["SEO", "Editorial", "Social"],
    description: [
      "Own content calendar and tone-of-voice.",
      "Coordinate with designers for campaign assets.",
      "Analyze performance and iterate messaging.",
    ],
    salaryReal: "฿35,000 - ฿50,000 /mo",
    contactPerson: "Content Manager",
    aiMatchReason: "Bilingual skills.",
  },
  {
    id: 15,
    company: "Udon AI Lab",
    role: "Research Assistant (NLP)",
    location: "Udon Thani, TH",
    onsite: "Remote",
    rate: "฿900 /hour",
    salarySort: 900,
    type: "Part-Time",
    applicants: "2 /10",
    level: "Expert",
    time: "6d ago",
    sortIndex: 15,
    tags: ["NLP", "Thai Language", "Evaluation"],
    description: [
      "Assist with data curation and evaluation suites.",
      "Run experiments and report findings.",
      "Support paper writing and reproducibility.",
    ],
    salaryReal: "฿1,000 /hour",
    contactPerson: "Principal Researcher",
    aiMatchReason: "NLP research experience.",
  },
];
